-- 코드를 입력하세요

SELECT PRODUCT_CODE, SUM(p.PRICE*s.SALES_AMOUNT) as SALES 
from product p join OFFLINE_SALE s 
WHERE p.PRODUCT_ID = s.PRODUCT_ID 
GROUP BY s.PRODUCT_ID 
ORDER BY SALES DESC, PRODUCT_CODE ASC;